services:

  postgres:
    image: postgres:16
    container_name: perf_postgres
    environment:
      POSTGRES_DB: pruebarendimiento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    cpus: 1
    mem_limit: 1g
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tomcat:
    build: ./tomcat
    ports:
      - "8080:8080"
    cpus: 2
    mem_limit: 2g
    depends_on:
      - postgres

  webflux:
    build: ./webflux
    ports:
      - "8081:8081"
    cpus: 2
    mem_limit: 2g
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v3.5.4
    container_name: pruebarendimiento_prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:13.1.0
    container_name: pruebarendimiento_grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:

