global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "tomcat"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["tomcat:8080"]
  - job_name: "webflux"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["webflux:8081"]

